#!/bin/bash
scriptdir=$(dirname "$(readlink -f "$0")")

save_envvars() {
    for _var in "$@" ; do
        eval "[ -n \"\${$_var+x}\" ] && printf '%s=%s\n' '$_var' \"'\$$_var'\""
    done
    unset _var
}

savedenvvars="$(save_envvars PKGDEST SRCDEST SRCPKGDEST LOGDEST BUILDDIR PKGEXT SRCEXT GPGKEY PACKAGER CARCH)"
set -a
for x in "$HOME/${XDG_CONFIG_HOME:-.config}/pacman/makepkg.conf" "$HOME/.makepkg.conf" "/etc/makepkg.conf" ; do
    if [ -r "$x" ]; then
        . "$x"
        break
    fi
done
eval "$savedenvvars"
set +a

exec "$scriptdir"/aur.py "$@"
