#!/bin/bash
scriptdir=$(dirname "$(readlink -f "$0")")

save_envvars() {
    for _var in "$@" ; do
        eval "[ -n \"\${$_var+x}\" ] && printf '%s=%s\n' '$_var' \"'\$$_var'\""
    done
    unset _var
}

for MAKEPKG_CONF in "$HOME/${XDG_CONFIG_HOME:-.config}/pacman/makepkg.conf" "$HOME/.makepkg.conf" "/etc/makepkg.conf" ; do
    if [ -r "$MAKEPKG_CONF" ]; then
        savedenvvars="$(save_envvars PKGDEST SRCDEST SRCPKGDEST LOGDEST BUILDDIR PKGEXT SRCEXT GPGKEY PACKAGER CARCH)"
        set -a
        . "$MAKEPKG_CONF"
        eval "$savedenvvars"
        set +a
        export MAKEPKG_CONF
        break
    fi
done

# exec "$scriptdir"/aur.py "$@"
