#!/bin/bash

SCRIPTDIR=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
if ! [[ -f "$SCRIPTDIR/arch-setup-shared" ]]; then
    echo "error: $SCRIPTDIR/arch-setup-shared not found" >&2
    exit 1
fi
. "$SCRIPTDIR/arch-setup-shared"



arch_chroot() {
    if [[ "$*" != "" ]]; then
        arch-chroot "$ROOT_MOUNTPOINT" /bin/bash -c "$*"
    else
        arch-chroot "$ROOT_MOUNTPOINT"
    fi
}
arch_pacstrap() {
    pacstrap $ROOT_MOUNTPOINT "$@"
}



cp -rf -T "$SCRIPTDIR/root/etc" "/etc"

. "$SCRIPTDIR/preinstall/configure-partition-scheme"
. "$SCRIPTDIR/preinstall/configure-luks"
. "$SCRIPTDIR/preinstall/configure-lvm"
. "$SCRIPTDIR/preinstall/format-partitions"

. "$SCRIPTDIR/preinstall/configure-mirrorlist"
. "$SCRIPTDIR/preinstall/install-base-system"
. "$SCRIPTDIR/preinstall/install-bootloader"

. "$SCRIPTDIR/preinstall/configure-keymap"
. "$SCRIPTDIR/preinstall/configure-timedate"
. "$SCRIPTDIR/preinstall/configure-locale"
. "$SCRIPTDIR/preinstall/configure-fstab"
. "$SCRIPTDIR/preinstall/configure-hostname"
. "$SCRIPTDIR/preinstall/configure-mkinitcpio"
. "$SCRIPTDIR/preinstall/configure-root-user"

print_info "Copying installation scripts to root home directory"
cp -rf -t "${ROOT_MOUNTPOINT}${HOME}" "$SCRIPTDIR"

print_info "Unmounting partitions. Please reboot the system without the live CD, then run the second script"
umount -R "$ROOT_MOUNTPOINT"
