zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 0
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' substitute 1

autoload -Uz compinit promptinit
compinit
promptinit

autoload zmv
alias zcp='zmv -C' zln='zmv -L'

PROMPT='%B%F{green}%n@%m%f%b:%B%F{blue}%~%f%b%(!.#.$) '
RPROMPT=''
HISTFILE=~/.bash_history
HISTSIZE=1000
SAVEHIST=1000

setopt histignoredups
setopt ksh_arrays
setopt auto_cd

bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "\e[3~" delete-char

for plugin in $(find /usr/share/zsh/plugins -mindepth 1 -maxdepth 1 -type d -printf "%f\n") ; do
    source /usr/share/zsh/plugins/$plugin/$plugin.zsh
done
unset plugin

command -v pyenv 1>/dev/null 2>&1 && eval "$(pyenv init -)"
command -v pyenv-virtualenv 1>/dev/null 2>&1 && eval "$(pyenv virtualenv-init -)"
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh
